import type { Arena } from "./types";

// Hard-coded roster used until Step 05 wires up the real AI scan.
// Each fighter: 5 moves (4 normal + 1 special LAST), at least 3 with effects
// that fit the object, and 2 object-flavoured abilities.
export const MOCK_ARENA: Arena = {
  arenaName: "The Desk of Destiny",
  fighters: [
    {
      id: "chai",
      objectName: "chai cup",
      fighterName: "Chai Titan",
      emoji: "☕",
      title: "The Steaming Menace",
      catchphrase: "You're about to get steeped.",
      hp: 68,
      type: "heat",
      weakness: "blunt",
      moves: [
        {
          name: "Scalding Splash",
          type: "heat",
          power: 20,
          description: "A tidal wave of cardamom-scented regret.",
          effect: { kind: "burn", chance: 55 },
        },
        {
          name: "Milk Foam Slam",
          type: "blunt",
          power: 16,
          description: "Whips foam into a passive-aggressive dairy tsunami.",
        },
        {
          name: "Steam Cloud",
          type: "heat",
          power: 12,
          description: "Wafts a disorienting cloud of fragrant steam.",
          effect: { kind: "weaken", chance: 45 },
        },
        {
          name: "Cardamom Rush",
          type: "chaos",
          power: 18,
          description: "A jittery caffeine spike nobody asked for.",
          effect: { kind: "boost", chance: 35 },
        },
        {
          name: "Third Cup Meltdown",
          type: "heat",
          power: 33,
          description: "Pure caffeine rage boils over the rim.",
          isSpecial: true,
          effect: { kind: "burn", chance: 40 },
        },
      ],
      abilities: [
        { name: "Hothead Brew", description: "Deals more damage the closer it gets to the dregs.", kind: "hothead" },
        { name: "Ceramic Hide", description: "Its thick mug walls shrug off incoming hits.", kind: "thick_skin" },
      ],
    },
    {
      id: "laptop",
      objectName: "laptop",
      fighterName: "Laptop Lord",
      emoji: "💻",
      title: "The Screen of Judgment",
      catchphrase: "Have you tried turning off your dreams?",
      hp: 118,
      type: "electric",
      weakness: "liquid",
      moves: [
        {
          name: "Fan Overclock",
          type: "electric",
          power: 19,
          description: "Spins fans to eleven purely out of spite.",
        },
        {
          name: "Notification Barrage",
          type: "electric",
          power: 13,
          description: "Fires forty unread pings straight into your soul.",
          effect: { kind: "stun", chance: 35 },
        },
        {
          name: "Keyboard Smash",
          type: "blunt",
          power: 17,
          description: "Types entirely in furious all-caps rage.",
        },
        {
          name: "Forced Update",
          type: "chaos",
          power: 11,
          description: "Restarts mid-fight for 'important security patches'.",
          effect: { kind: "shield", chance: 50 },
        },
        {
          name: "Blue Screen of Doom",
          type: "electric",
          power: 34,
          description: "Crashes reality itself for point-four glorious seconds.",
          isSpecial: true,
          effect: { kind: "stun", chance: 30 },
        },
      ],
      abilities: [
        { name: "Power Surge", description: "Its opening move hits with a jolt of full charge.", kind: "first_strike" },
        { name: "Full Battery Luck", description: "A charged cell means suspiciously frequent critical hits.", kind: "lucky" },
      ],
    },
    {
      id: "stapler",
      objectName: "stapler",
      fighterName: "Sir Stapleton",
      emoji: "📎",
      title: "The Cubicle's Cruelest Blade",
      catchphrase: "Bow before the office's sharpest little tyrant.",
      hp: 78,
      type: "sharp",
      weakness: "chaos",
      moves: [
        {
          name: "Staple Volley",
          type: "sharp",
          power: 21,
          description: "Fires forty rounds of pure office aggression.",
          effect: { kind: "drain", chance: 45 },
        },
        {
          name: "Jammed Fury",
          type: "chaos",
          power: 14,
          description: "Jams mid-swing, then explodes in petty chaos.",
        },
        {
          name: "Paper Cut Combo",
          type: "sharp",
          power: 15,
          description: "A hundred tiny, unforgivable paper cuts.",
          effect: { kind: "drain", chance: 55 },
        },
        {
          name: "Desk Slam",
          type: "blunt",
          power: 17,
          description: "Body-slams the stationery tray in a rage.",
        },
        {
          name: "Full Cartridge Unload",
          type: "sharp",
          power: 32,
          description: "Empties the entire cartridge in one righteous fury.",
          isSpecial: true,
          effect: { kind: "drain", chance: 40 },
        },
      ],
      abilities: [
        { name: "Keen Edge", description: "Its sharpened jaw finds critical hits more often.", kind: "lucky" },
        { name: "Loaded Spring", description: "Recoils hard, reflecting some damage right back.", kind: "thorns" },
      ],
    },
    {
      id: "headphones",
      objectName: "headphones",
      fighterName: "DJ Earquake",
      emoji: "🎧",
      title: "The Bassline Apocalypse",
      catchphrase: "Volume's stuck at eleven, baby, deal with it.",
      hp: 82,
      type: "chaos",
      weakness: "sharp",
      moves: [
        {
          name: "Bass Drop",
          type: "chaos",
          power: 21,
          description: "Drops a bass so deep it cracks drywall.",
        },
        {
          name: "Tangled Wire Whip",
          type: "sharp",
          power: 16,
          description: "Lashes out with permanently, mysteriously knotted cables.",
        },
        {
          name: "Static Screech",
          type: "chaos",
          power: 12,
          description: "A piercing static burst that scrambles focus.",
          effect: { kind: "weaken", chance: 50 },
        },
        {
          name: "Noise Cancel Trick",
          type: "blunt",
          power: 13,
          description: "Blocks out the world, and incidentally the next hit.",
          effect: { kind: "stun", chance: 30 },
        },
        {
          name: "Feedback Screech",
          type: "chaos",
          power: 35,
          description: "Unleashes a screech that ends every conversation instantly.",
          isSpecial: true,
          effect: { kind: "weaken", chance: 45 },
        },
      ],
      abilities: [
        { name: "Spiky Earcups", description: "Its padded cups bite back when squeezed too hard.", kind: "thorns" },
        { name: "Surprise Encore", description: "Somehow survives one hit that should've ended it.", kind: "last_stand" },
      ],
    },
    {
      id: "bottle",
      objectName: "water bottle",
      fighterName: "Hydro Warden",
      emoji: "🧴",
      title: "The Liquid Enforcer",
      catchphrase: "Stay thirsty. Actually, please don't. I'm serious.",
      hp: 88,
      type: "liquid",
      weakness: "electric",
      moves: [
        {
          name: "Pressure Squirt",
          type: "liquid",
          power: 19,
          description: "Blasts a jet reserved for gym-bag emergencies.",
        },
        {
          name: "Cap Flick Combo",
          type: "blunt",
          power: 13,
          description: "Flicks its cap like a tiny plastic ninja.",
        },
        {
          name: "Electrolyte Refill",
          type: "liquid",
          power: 10,
          description: "Chugs a suspiciously glowing electrolyte mix.",
          effect: { kind: "heal", chance: 60 },
        },
        {
          name: "Condensation Slick",
          type: "liquid",
          power: 14,
          description: "Leaves a slippery puddle nobody saw coming.",
          effect: { kind: "weaken", chance: 40 },
        },
        {
          name: "Tsunami Chug",
          type: "liquid",
          power: 31,
          description: "Empties itself entirely in one dramatic gulp.",
          isSpecial: true,
          effect: { kind: "heal", chance: 35 },
        },
      ],
      abilities: [
        { name: "Refill Station", description: "Tops itself back up a little every single turn.", kind: "regen" },
        { name: "Reinforced Bottle", description: "Its tough plastic shell absorbs a chunk of every hit.", kind: "thick_skin" },
      ],
    },
    {
      id: "notebook",
      objectName: "notebook",
      fighterName: "Professor Scribbles",
      emoji: "📓",
      title: "The Ink-Stained Tyrant",
      catchphrase: "This will definitely be on the test.",
      hp: 100,
      type: "blunt",
      weakness: "heat",
      moves: [
        {
          name: "Spine Slam",
          type: "blunt",
          power: 21,
          description: "Slams shut with the force of deadlines.",
        },
        {
          name: "Paper Cut Flurry",
          type: "sharp",
          power: 17,
          description: "Delivers a hundred tiny, unforgivable paper cuts.",
        },
        {
          name: "Hardcover Guard",
          type: "blunt",
          power: 11,
          description: "Snaps shut tight behind its reinforced cover.",
          effect: { kind: "shield", chance: 55 },
        },
        {
          name: "Dog-Eared Taunt",
          type: "chaos",
          power: 14,
          description: "Flashes a dog-eared page like a badge of honor.",
          effect: { kind: "boost", chance: 40 },
        },
        {
          name: "Pop Quiz Panic",
          type: "chaos",
          power: 30,
          description: "Springs a surprise quiz nobody studied for.",
          isSpecial: true,
          effect: { kind: "shield", chance: 35 },
        },
      ],
      abilities: [
        { name: "Hardback Binding", description: "Its rigid cover soaks up a chunk of every blow.", kind: "thick_skin" },
        { name: "Dog-Eared Comeback", description: "One page always survives to fight another round.", kind: "last_stand" },
      ],
    },
  ],
};
