import type { Arena } from "./types";

// Hard-coded roster used until Step 05 wires up the real AI scan.
export const MOCK_ARENA: Arena = {
  arenaName: "The Desk of Destiny",
  fighters: [
    {
      id: "chai",
      objectName: "chai cup",
      fighterName: "Chai Titan",
      emoji: "☕",
      title: "The Steaming Menace",
      catchphrase: "You're about to get steeped.",
      hp: 68,
      type: "heat",
      weakness: "blunt",
      moves: [
        {
          name: "Scalding Splash",
          type: "heat",
          power: 22,
          description: "A tidal wave of cardamom-scented regret.",
        },
        {
          name: "Milk Foam Slam",
          type: "blunt",
          power: 15,
          description: "Whips foam into a passive-aggressive dairy tsunami.",
        },
        {
          name: "Third Cup Meltdown",
          type: "heat",
          power: 33,
          description: "Pure caffeine rage boils over the rim.",
          isSpecial: true,
        },
      ],
    },
    {
      id: "laptop",
      objectName: "laptop",
      fighterName: "Laptop Lord",
      emoji: "💻",
      title: "The Screen of Judgment",
      catchphrase: "Have you tried turning off your dreams?",
      hp: 118,
      type: "electric",
      weakness: "liquid",
      moves: [
        {
          name: "Fan Overclock",
          type: "electric",
          power: 18,
          description: "Spins fans to eleven purely out of spite.",
        },
        {
          name: "Keyboard Smash",
          type: "blunt",
          power: 15,
          description: "Types entirely in furious all-caps rage.",
        },
        {
          name: "Blue Screen of Doom",
          type: "electric",
          power: 34,
          description: "Crashes reality itself for point-four glorious seconds.",
          isSpecial: true,
        },
      ],
    },
    {
      id: "stapler",
      objectName: "stapler",
      fighterName: "Sir Stapleton",
      emoji: "📎",
      title: "The Cubicle's Cruelest Blade",
      catchphrase: "Bow before the office's sharpest little tyrant.",
      hp: 78,
      type: "sharp",
      weakness: "chaos",
      moves: [
        {
          name: "Staple Volley",
          type: "sharp",
          power: 20,
          description: "Fires forty rounds of pure office aggression.",
        },
        {
          name: "Jammed Fury",
          type: "chaos",
          power: 14,
          description: "Jams mid-swing, then explodes in petty chaos.",
        },
        {
          name: "Full Cartridge Unload",
          type: "sharp",
          power: 32,
          description: "Empties the entire cartridge in one righteous fury.",
          isSpecial: true,
        },
      ],
    },
    {
      id: "headphones",
      objectName: "headphones",
      fighterName: "DJ Earquake",
      emoji: "🎧",
      title: "The Bassline Apocalypse",
      catchphrase: "Volume's stuck at eleven, baby, deal with it.",
      hp: 82,
      type: "chaos",
      weakness: "sharp",
      moves: [
        {
          name: "Bass Drop",
          type: "chaos",
          power: 22,
          description: "Drops a bass so deep it cracks drywall.",
        },
        {
          name: "Tangled Wire Whip",
          type: "sharp",
          power: 16,
          description: "Lashes out with permanently, mysteriously knotted cables.",
        },
        {
          name: "Feedback Screech",
          type: "chaos",
          power: 35,
          description: "Unleashes a screech that ends every conversation instantly.",
          isSpecial: true,
        },
      ],
    },
    {
      id: "bottle",
      objectName: "water bottle",
      fighterName: "Hydro Warden",
      emoji: "🧴",
      title: "The Liquid Enforcer",
      catchphrase: "Stay thirsty. Actually, please don't. I'm serious.",
      hp: 88,
      type: "liquid",
      weakness: "electric",
      moves: [
        {
          name: "Pressure Squirt",
          type: "liquid",
          power: 18,
          description: "Blasts a jet reserved for gym-bag emergencies.",
        },
        {
          name: "Cap Flick Combo",
          type: "blunt",
          power: 12,
          description: "Flicks its cap like a tiny plastic ninja.",
        },
        {
          name: "Tsunami Chug",
          type: "liquid",
          power: 31,
          description: "Empties itself entirely in one dramatic gulp.",
          isSpecial: true,
        },
      ],
    },
    {
      id: "notebook",
      objectName: "notebook",
      fighterName: "Professor Scribbles",
      emoji: "📓",
      title: "The Ink-Stained Tyrant",
      catchphrase: "This will definitely be on the test.",
      hp: 100,
      type: "blunt",
      weakness: "heat",
      moves: [
        {
          name: "Spine Slam",
          type: "blunt",
          power: 20,
          description: "Slams shut with the force of deadlines.",
        },
        {
          name: "Paper Cut Flurry",
          type: "sharp",
          power: 17,
          description: "Delivers a hundred tiny, unforgivable paper cuts.",
        },
        {
          name: "Pop Quiz Panic",
          type: "chaos",
          power: 30,
          description: "Springs a surprise quiz nobody studied for.",
          isSpecial: true,
        },
      ],
    },
  ],
};
